config:
  # 当前的浏览器路径配置路径
  driver: "E:\\code\\stock\\chrome\\chromedriver.exe"
  browser: "E:\\code\\stock\\chrome\\chrome.exe"
  in: "入库单.xlsx"
  out: "出库单.xlsx"

# 登陆信息
login:
  url:  "网址"
  user: "账号"
  password: "密码"

# 入库的选择条件
in:
  "鸡蛋":
    "名称": "鸡蛋"
    "单位": "个"
  "排骨":
    "名称": "排骨"
  "羊肉":
    "名称": "整羊"
  "鸡肉":
    "名称": "山黄鸡肉"
  "牛肉":
    "名称": "牛肉"
    "单位": "斤"
  "大腾小粉":
    "名称": "大腾小粉"
  "郫县红油豆瓣酱":
    "单位": "瓶"
    "分类": "调料"
  "红蒜苗":
    "名称": "红蒜苗"

# 出库判断条件
out:
  "米":
    "名称": "君有福小町香米"
  "猪肉":
    "名称": "猪肉"


sign: "9295ab9d95e683a6df00bc8c646bde1b7a44d9aba402c5c10176a61f1e5a4fd03c3f98f8380c2670197d2063d6212ffc69943a366ea689019cc01089f8815722"
